### ISSUE TITLE
I personally suggest that use the new things which help you easily

### ISSUE THREAD

**Issue by annibuliful** [bridgetsarah/mean#9]
1. I don't know what your NodeJS question. If you use Node 8 or newer, You should use **Async/Await** instead of **Callback**
2. You should separate your websocket service to small function, you can see my simple backend https://github.com/lagmanzaza/chatty/tree/master/backend/src/websocket

Thank you, sir.

**Comment by bridgetsarah** [comment]
Much appreciated! I'll see if I can do this with the application, might be easier!

**Comment by annibuliful** [comment]
If you have some problems, you can ask me via this issue. I will try to help you as I can, sir.
